on: push
name: Build and Deploy to Habor registry

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup gcloud
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Configure docker
        uses: docker/login-action@v1
        with:
          registry: "harbor.apps.ocp.nmandadhi.com"
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: "harbor.apps.ocp.nmandadhi.com/library/s2i-jdk8:$GITHUB_SHA"
