on: push
name: Build and Deploy to Habor registry

env:
  PROJECT_ID: library
  DEPLOYMENT_NAME: s2i-jdk8
  IMAGE: s2i-jdk8
  REPOSITORY: harbor.apps.ocp.nmandadhi.com

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Configure docker
        uses: docker/login-action@v1
        with:
          registry: $REPOSITORY
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: "$REPOSITORY/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
